repo = "github.com/buger/goreplay"
rule = "codelingo/go/default-in-type-switch"
sha = "ffc1a09ca1e465dc1b67efc151dab2771e1086c7"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 56
  filepath = "vendor/github.com/mattbaird/elastigo/lib/coreupdate.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 440
  filepath = "vendor/github.com/araddon/gou/jsonhelper.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 15
  filepath = "vendor/github.com/rcrowley/go-metrics/json.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 87
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 329
  filepath = "vendor/github.com/araddon/gou/jsonhelper.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 185
  filepath = "vendor/github.com/rcrowley/go-metrics/registry.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 194
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 16
  filepath = "vendor/github.com/rcrowley/go-metrics/syslog.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 71
  filepath = "vendor/github.com/rcrowley/go-metrics/opentsdb.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 181
  filepath = "vendor/github.com/araddon/gou/jsonhelper.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 28
  filepath = "vendor/github.com/rcrowley/go-metrics/writer.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 306
  filepath = "vendor/github.com/araddon/gou/jsonhelper.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 13
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 278
  filepath = "vendor/github.com/araddon/gou/jsonhelper.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 248
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 60
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 114
  filepath = "vendor/github.com/davecgh/go-spew/spew/common.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 84
  filepath = "vendor/github.com/mattbaird/elastigo/lib/coreupdate.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 132
  filepath = "vendor/github.com/rcrowley/go-metrics/registry.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 67
  filepath = "vendor/github.com/rcrowley/go-metrics/graphite.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 122
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 23
  filepath = "vendor/github.com/rcrowley/go-metrics/log.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 313
  filepath = "vendor/github.com/araddon/gou/coerce.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 306
  filepath = "vendor/github.com/Shopify/sarama/mockresponses.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 80
  filepath = "vendor/github.com/mattbaird/elastigo/lib/searchfilter.go"
  fixed = false
  ignored = "vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 557
  filepath = "vendor/github.com/araddon/gou/jsonhelper.go"
  fixed = false
  ignored = "vendor"
