repo = "github.com/ngchain/ngcore"
rule = "codelingo/effective-go/initialize-using-composite-literal"
sha = "16e762e18441963bdb7adf2b32e6f13830196e69"

[[issues]]
  filepath = "ngsheet/handle.go"
  fileline = 367
  comment = "Initialize convener using a composite literal to simplify the code. [as specified in Effective Go](https://golang.org/doc/effective_go.html#composite_literals)"

[[issues]]
  filepath = "ngsheet/handle.go"
  fileline = 318
  comment = "Initialize convener using a composite literal to simplify the code. [as specified in Effective Go](https://golang.org/doc/effective_go.html#composite_literals)"
