repo = "github.com/flynn/flynn"
rule = "codelingo/go/reassigned-error"
sha = "755c95684ffe290c64b8be114c2963aa2850b531"

[[issues]]
  filepath = "host/volume/manager/persistence_test.go"
  fileline = 282
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "pkg/term/ascii_test.go"
  fileline = 15
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "pkg/mux/mux_test.go"
  fileline = 20
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "discoverd/health/check.go"
  fileline = 65
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "host/cli/discoverd.go"
  fileline = 44
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "controller/worker/domain_migration/domain_migration.go"
  fileline = 225
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "flannel/pkg/ip/tun.go"
  fileline = 34
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "controller/examples/examples.go"
  fileline = 36
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "host/volume/manager/persistence_test.go"
  fileline = 391
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "controller/examples/examples.go"
  fileline = 206
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "host/cli/volume.go"
  fileline = 60
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "router/proxyproto/protocol_test.go"
  fileline = 67
  comment = "Error was not checked before reassignment"
