repo = "github.com/joewalnes/websocketd"
rule = "codelingo/go/non-directional-chan"
sha = "7c9231ab6342ce6e9ede8af036cd2e940c2598c5"

[[issues]]
  filepath = "libwebsocketd/process_endpoint.go"
  fileline = 89
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "libwebsocketd/websocket_endpoint.go"
  fileline = 43
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "libwebsocketd/endpoint.go"
  fileline = 11
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 55
  comment = "Returned channels or channel arguments should generally have a direction."
