repo = "github.com/nsqio/nsq"
rule = "codelingo/go/non-exiting-goroutine"
sha = "8db8c50e5e583bbde3528de93a5e363edd788868"

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1753
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "nsqd/http_test.go"
  fileline = 918
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "nsqd/stats_test.go"
  fileline = 136
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1664
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1738
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1679
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "nsqd/stats_test.go"
  fileline = 145
  comment = "This goroutine does not exit and may cause a resource leak."
