repo = "github.com/google/cadvisor"
rule = "codelingo/go/break-select-in-for"
sha = "7f840ac879cf7409586233865f96b0b74e1bda51"

[[issues]]
  filepath = "manager/manager.go"
  fileline = 321
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
