repo = "github.com/morya/gopractice"
rule = "codelingo/go/break-select-in-for"
sha = "308e6732591c092d8cedde2734660931c94fd927"

[[issues]]
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
  fileline = 168
  filepath = "gw_log_consumer/app.go"
  fixed = false
  ignored = "weird logic, but intentional"
