repo = "github.com/zyedidia/micro"
rule = "codelingo/go/non-directional-chan"
sha = "052a36b896bb31f1148c631cc29ab87abf013b1f"

[[issues]]
  filepath = "internal/screen/screen.go"
  fileline = 48
  comment = "Returned channels or channel arguments should generally have a direction."
