repo = "github.com/cyfdecyf/cow"
rule = "codelingo/go/non-directional-chan"
sha = "41c0fb157c8b939b724ae0d58dad3a1b7cd2e811"

[[issues]]
  filepath = "conn_pool.go"
  fileline = 176
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "proxy.go"
  fileline = 1069
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "conn_pool.go"
  fileline = 48
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "conn_pool.go"
  fileline = 33
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "conn_pool.go"
  fileline = 143
  comment = "Returned channels or channel arguments should generally have a direction."
