repo = "github.com/lomik/go-carbon"
rule = "codelingo/go/non-directional-chan"
sha = "96dd8d509cdc6874283123e025c90be304ce6ee7"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 78
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 68
  filepath = "persister/whisper.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 168
  filepath = "receiver/udp/udp.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 9
  filepath = "points/glue.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 9
  filepath = "points/glue.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 20
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 20
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 28
  filepath = "persister/whisper.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 287
  filepath = "cache/carbonlink.go"
  fixed = false
  ignored = "unused"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 105
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 60
  filepath = "persister/throttle.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 72
  filepath = "api/api.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 71
  filepath = "helper/stoppable.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 260
  filepath = "receiver/tcp/tcp.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 70
  filepath = "helper/stoppable.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 335
  filepath = "receiver/tcp/tcp.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 32
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 32
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 81
  filepath = "carbon/collector.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 59
  filepath = "persister/throttle.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 10
  filepath = "persister/whisper_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 36
  filepath = "cache/writeout_queue.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 36
  filepath = "cache/writeout_queue.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 280
  filepath = "cache/carbonlink.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 59
  filepath = "persister/throttle.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 231
  filepath = "tags/queue.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 67
  filepath = "api/api.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 348
  filepath = "receiver/tcp/tcp.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 107
  filepath = "receiver/udp/udp.go"
  fixed = false
  ignored = "unused"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 104
  filepath = "persister/throttle.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 14
  filepath = "helper/stoppable.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 190
  filepath = "carbon/collector.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 165
  filepath = "tags/queue.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 194
  filepath = "receiver/tcp/tcp.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 364
  filepath = "receiver/tcp/tcp.go"
  fixed = false
  ignored = "unusued"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 16
  filepath = "persister/whisper_stop_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 103
  filepath = "persister/throttle.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 13
  filepath = "helper/stoppable.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 380
  filepath = "receiver/tcp/tcp.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 24
  filepath = "cache/queue.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 103
  filepath = "persister/throttle.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 377
  filepath = "persister/whisper.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 46
  filepath = "helper/stoppable.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 160
  filepath = "receiver/udp/udp.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 16
  filepath = "persister/whisper_stop_test.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 39
  filepath = "helper/stoppable.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 20
  filepath = "persister/whisper_stop_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 65
  filepath = "carbon/collector.go"
  fixed = true
  ignored = ""
