repo = "github.com/kphf1995cm/MIT-6.824"
rule = "codelingo/go/non-directional-chan"
sha = "6984407071aac4c5f0f8d8b48975d1ab742cef4e"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 218
  filepath = "src/raft/raft.go"
  fixed = false
  ignored = "not used"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 14
  filepath = "src/mapreduce/schedule.go"
  fixed = false
  ignored = "not used"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 122
  filepath = "src/kvraft/test_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 799
  filepath = "src/raft/test_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 85
  filepath = "src/mapreduce/master.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 45
  filepath = "src/kvraft/test_test.go"
  fixed = true
  ignored = ""
