repo = "github.com/nickysemenza/gola"
rule = "error-reassign"
sha = "29d749168e8b7502cd690500da427c70b9f43052"

[[issues]]
  fileline = 50
  filepath = "utils.go"
  fixed = false
  ignored = "fp. investigate. this is a bug"
