repo = "github.com/BeFunes/go-test"
rule = "codelingo/go/insecure-http-connection"
sha = "f0b6715757838d21fe9a88b7e8103531e15c23cb"

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 124
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
