repo = "github.com/go-gitea/gitea"
rule = "codelingo/go/break-select-in-for"
sha = "089b34858ce1ce3101b13fa8e14e4e56e0a02a90"

[[issues]]
  filepath = "modules/queue/queue_wrapped.go"
  fileline = 56
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
