repo = "github.com/tobyhede/go-underscore"
rule = "codelingo/go/non-directional-chan"
sha = "ea55fc9569918f099b1dfa785088434e5c53544d"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 128
  filepath = "map.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 81
  filepath = "underscore.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 135
  filepath = "map.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 75
  filepath = "map.go"
  fixed = true
  ignored = ""
