repo = "github.com/Masterminds/glide"
rule = "codelingo/go/default-in-type-switch"
sha = "b94b39d657d8abcccba6545e148f1201aee6ffec"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 413
  filepath = "vendor/gopkg.in/yaml.v2/decode.go"
  fixed = false
  ignored = "embedded switch. all cases covered"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 711
  filepath = "vendor/github.com/codegangsta/cli/flag.go"
  fixed = false
  ignored = "in vendor"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 182
  filepath = "msg/msg.go"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 382
  filepath = "vendor/gopkg.in/yaml.v2/decode.go"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 203
  filepath = "vendor/github.com/Masterminds/vcs/vcs_remote_lookup.go"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 436
  filepath = "vendor/gopkg.in/yaml.v2/decode.go"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 442
  filepath = "vendor/gopkg.in/yaml.v2/decode.go"
