repo = "github.com/sundy-li/wechat_brain"
rule = "codelingo/go/non-directional-chan"
sha = "b49fc95d3e06b2841dc394c86831ca07c04d8803"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 416
  filepath = "vendor/github.com/boltdb/bolt/tx.go"
  fixed = false
  ignored = "archived"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 381
  filepath = "vendor/github.com/boltdb/bolt/tx.go"
  fixed = false
  ignored = "archived"
