repo = "github.com/grafana/loki"
rule = "codelingo/go/unchecked-type-assertion"
sha = "8e5fa03de3b3cf7efa15e4959bd5b7decae2d944"

[[issues]]
  filepath = "pkg/querier/queryrange/codec.go"
  fileline = 231
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/stats_test.go"
  fileline = 88
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/targets/journaltarget_test.go"
  fileline = 298
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/targets/journaltarget_test.go"
  fileline = 214
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/targets/syslogtarget.go"
  fileline = 249
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/stats_test.go"
  fileline = 108
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 199
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/server/ui/assets_vfsdata.go"
  fileline = 595
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 236
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/fluent-bit/out_loki.go"
  fileline = 108
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/targets/journaltarget_test.go"
  fileline = 162
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/fluent-bit/loki.go"
  fileline = 77
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/fluent-bit/loki.go"
  fileline = 161
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/split_by_interval.go"
  fileline = 137
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ingester/transfer.go"
  fileline = 212
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/querier.go"
  fileline = 390
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/stats_test.go"
  fileline = 78
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ingester/flush.go"
  fileline = 185
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/util/query_string_builder_test.go"
  fileline = 45
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 174
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 279
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/targets/journaltarget_test.go"
  fileline = 256
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/client/multi_test.go"
  fileline = 33
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 221
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logql/range_vector.go"
  fileline = 149
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logentry/stages/metrics.go"
  fileline = 294
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logql/engine.go"
  fileline = 191
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 185
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logql/shardmapper.go"
  fileline = 23
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/stats.go"
  fileline = 90
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/ordering.go"
  fileline = 76
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 114
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/querier.go"
  fileline = 321
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/fluent-bit/loki.go"
  fileline = 98
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/querier.go"
  fileline = 593
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/memchunk.go"
  fileline = 113
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logql/evaluator.go"
  fileline = 114
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/fluent-bit/out_loki.go"
  fileline = 88
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/memchunk.go"
  fileline = 652
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logentry/stages/pipeline.go"
  fileline = 42
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logentry/stages/metrics.go"
  fileline = 159
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chunkenc/pool.go"
  fileline = 92
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/logentry/stages/util.go"
  fileline = 148
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/fluent-bit/loki.go"
  fileline = 183
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/promtail/targets/journaltarget_test.go"
  fileline = 107
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/querier/queryrange/codec.go"
  fileline = 322
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
