repo = "github.com/yongliu1992/go_learn"
rule = "codelingo/go/non-directional-chan"
sha = "a14870451ad0ae4cd1ed0f29bcfe42663b876ede"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 13
  filepath = "routine/main.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 20
  filepath = "routine/main.go"
  fixed = true
  ignored = ""
