repo = "github.com/sundy-li/go_commons"
rule = "codelingo/go/break-select-in-for"
sha = "f22c3f2760b83ba2cbc218a64df4dfa38d62535b"

[[issues]]
  filepath = "libs/kafka/reader.go"
  fileline = 497
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
