repo = "github.com/flynn/flynn"
rule = "codelingo/lomik-go-carbon/missing-stop-ticker"
sha = "755c95684ffe290c64b8be114c2963aa2850b531"

[[issues]]
  filepath = "host/monitor.go"
  fileline = 126
  comment = "Stop the ticker to release associated resources."
