repo = "github.com/jesseduffield/lazydocker"
rule = "codelingo/go/break-select-in-for"
sha = "10617da5608990bf4911142745d31566bac6964a"

[[issues]]
  filepath = "vendor/github.com/Microsoft/go-winio/pipe.go"
  fileline = 385
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "vendor/github.com/jesseduffield/termbox-go/api.go"
  fileline = 99
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
