repo = "github.com/go-gitea/gitea"
rule = "codelingo/go/non-exiting-goroutine"
sha = "089b34858ce1ce3101b13fa8e14e4e56e0a02a90"

[[issues]]
  filepath = "modules/graceful/manager_unix.go"
  fileline = 81
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "modules/git/commit.go"
  fileline = 501
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "modules/templates/helper.go"
  fileline = 426
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "routers/repo/lfs.go"
  fileline = 485
  comment = "This goroutine does not exit and may cause a resource leak."
