repo = "github.com/influxdata/telegraf"
rule = "codelingo/go/break-select-in-for"
sha = "df145c7e564c8ba0d4722a7a5ab96eb36834e1e0"

[[issues]]
  filepath = "agent/agent.go"
  fileline = 470
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
