repo = "github.com/iawia002/annie"
rule = "codelingo/go/non-exiting-goroutine"
sha = "c24fbc04b8260cc5923af12be9baf30d35735325"

[[issues]]
  filepath = "downloader/downloader.go"
  fileline = 336
  comment = "This goroutine does not exit and may cause a resource leak."
