repo = "github.com/SimonWaldherr/golibs"
rule = "codelingo/go/ticker-in-for-select"
sha = "d8150802aaa814bf0cba43fa97d6db29ff67c8a6"

[[issues]]
  filepath = "arg/arg.go"
  fileline = 52
  comment = "Make one ticker as opposed to making a new timer each iteration."
