repo = "github.com/edumco/docker-slim"
rule = "codelingo/go/non-directional-chan"
sha = "abba44d7e861c3df3f495315b5a73b21a8dd3ef0"

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 30
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 27
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 28
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 29
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 31
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 32
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/monitors/pevent/monitor.go"
  fileline = 17
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/monitors/ptrace/monitor.go"
  fileline = 48
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/monitors/ptrace/monitor.go"
  fileline = 45
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/monitors/fanotify/monitor.go"
  fileline = 36
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "internal/app/sensor/monitors/fanotify/monitor.go"
  fileline = 36
  comment = "Returned channels or channel arguments should generally have a direction."
