repo = "github.com/grpc/grpc-go"
rule = "codelingo/go/break-select-in-for"
sha = "98e4c7ad3eefd5c1a3cd647c004943ffab4f5722"

[[issues]]
  filepath = "balancer_conn_wrappers.go"
  fileline = 68
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "balancer.go"
  fileline = 317
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
