repo = "github.com/rstorr/cfssl"
rule = "codelingo/code-review-comments/avoid-meaningless-package-names"
sha = "9c027c93ba9e044bfffb63b78f9174075413bc9e"

[[issues]]
  filepath = "api/api_test.go"
  fileline = 1
  comment = "Avoid meaningless package names like util, common, misc, api, types, and interfaces. From [Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#package-names)"

[[issues]]
  filepath = "api/api.go"
  fileline = 2
  comment = "Avoid meaningless package names like util, common, misc, api, types, and interfaces. From [Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#package-names)"
