repo = "github.com/buger/goreplay"
rule = "codelingo/go/non-directional-chan"
sha = "ffc1a09ca1e465dc1b67efc151dab2771e1086c7"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 11
  filepath = "emitter.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 893
  filepath = "raw_socket_listener/listener.go"
  fixed = false
  ignored = "returned chan"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 837
  filepath = "vendor/github.com/google/gopacket/packet.go"
  fixed = false
  ignored = "returned chan"
