repo = "github.com/sundy-li/gos"
rule = "codelingo/go/insecure-http-connection"
sha = "f4a52987dd595ffbbf0ab0c2c79feacb5fb8e29e"

[[issues]]
  fileline = 46
  filepath = "email/ssl_email.go"
  fixed = true
  ignored = ""
