repo = "github.com/hashicorp/packer"
rule = "codelingo/go/break-select-in-for"
sha = "3892e0905a0e98b0548aac05646aeeda97b778dc"

[[issues]]
  filepath = "builder/vmware/common/driver_parser.go"
  fileline = 1720
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
