repo = "github.com/chrislusf/seaweedfs"
rule = "codelingo/go/non-directional-chan"
sha = "745f5d2a257785cd165111f2b20992d0422b90c8"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 194
  filepath = "weed/shell/command_volume_fsck.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 198
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 198
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 270
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 99
  filepath = "weed/shell/command_fs_meta_save.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 184
  filepath = "weed/command/filer_copy.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 339
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 339
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 99
  filepath = "weed/shell/command_fs_meta_save.go"
  fixed = false
  ignored = "unsure"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 437
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 80
  filepath = "weed/shell/command_fs_meta_save.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 250
  filepath = "weed/server/master_grpc_server.go"
  fixed = false
  ignored = "returned chan"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 223
  filepath = "weed/command/filer_copy.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 358
  filepath = "weed/command/benchmark.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 187
  filepath = "weed/shell/command_volume_fsck.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 141
  filepath = "weed/topology/store_replicate.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 72
  filepath = "weed/shell/command_fs_meta_save.go"
  fixed = true
  ignored = ""
