repo = "github.com/gadelkareem/proxy.webshare.io"
rule = "codelingo/go/unchecked-type-assertion"
sha = "2aed8e95b3157cd53cb1cbf4143756a0fa90df8c"

[[issues]]
  fileline = 82
  filepath = "client.go"
  fixed = true
  ignored = ""
