repo = "github.com/flynn/flynn"
rule = "codelingo/go/break-select-in-for"
sha = "755c95684ffe290c64b8be114c2963aa2850b531"

[[issues]]
  filepath = "vendor/google.golang.org/grpc/balancer.go"
  fileline = 317
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "vendor/github.com/flynn/que-go/worker.go"
  fileline = 75
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "vendor/golang.org/x/crypto/ssh/handshake.go"
  fileline = 266
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 859
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "discoverd/client/heartbeat.go"
  fileline = 167
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "discoverd/client/watch.go"
  fileline = 127
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "vendor/github.com/hashicorp/raft/raft.go"
  fileline = 933
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
