repo = "github.com/kphf1995cm/MIT-6.824"
rule = "codelingo/go/break-select-in-for"
sha = "6984407071aac4c5f0f8d8b48975d1ab742cef4e"

[[issues]]
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
  fileline = 66
  filepath = "src/shardkv/test_test.go"
  fixed = false
  ignored = "chan select"

[[issues]]
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
  fileline = 211
  filepath = "src/mapreduce/test_test.go"
  fixed = false
  ignored = "fp"
