repo = "github.com/wagoodman/dive"
rule = "codelingo/go/non-exiting-goroutine"
sha = "c6bb2372a8be13a80a81c00c04f9724970c0ae60"

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 96
  comment = "This goroutine does not exit and may cause a resource leak."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 129
  comment = "This goroutine does not exit and may cause a resource leak."
