repo = "github.com/SimonWaldherr/golibs"
rule = "codelingo/go/non-directional-chan"
sha = "d8150802aaa814bf0cba43fa97d6db29ff67c8a6"

[[issues]]
  filepath = "channel/channel.go"
  fileline = 30
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "channel/channel.go"
  fileline = 41
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "channel/channel.go"
  fileline = 47
  comment = "Returned channels or channel arguments should generally have a direction."
