repo = "github.com/SimonWaldherr/golibs"
rule = "codelingo/go/non-directional-chan"
sha = "d8150802aaa814bf0cba43fa97d6db29ff67c8a6"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 30
  filepath = "channel/channel.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 41
  filepath = "channel/channel.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 47
  filepath = "channel/channel.go"
  fixed = true
  ignored = ""
