repo = "github.com/nsqio/nsq"
rule = "codelingo/go/break-select-in-for"
sha = "8db8c50e5e583bbde3528de93a5e363edd788868"

[[issues]]
  filepath = "nsqd/statsd.go"
  fileline = 32
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
