repo = "github.com/SimonWaldherr/golibs"
rule = "codelingo/go/default-in-type-switch"
sha = "d8150802aaa814bf0cba43fa97d6db29ff67c8a6"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 37
  filepath = "node/node_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 81
  filepath = "foreach/foreach_test.go"
  fixed = false
  ignored = "in text"
