repo = "github.com/ipfs/go-ipfs"
rule = "codelingo/go/break-select-in-for"
sha = "1a2c88baae3aeb9ffe5ef64c9be1fc4fedef7d08"

[[issues]]
  filepath = "namesys/base.go"
  fileline = 57
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "namesys/dns.go"
  fileline = 89
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
