repo = "github.com/fatedier/frp"
rule = "codelingo/go/non-directional-chan"
sha = "8668fef136baceacf974f7ef4859d108d413a42e"

[[issues]]
  filepath = "client/proxy/proxy_manager.go"
  fileline = 32
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "client/proxy/proxy.go"
  fileline = 506
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "client/proxy/proxy.go"
  fileline = 524
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "models/nathole/nathole.go"
  fileline = 52
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "client/proxy/proxy.go"
  fileline = 490
  comment = "Returned channels or channel arguments should generally have a direction."
