repo = "github.com/rkt/rkt"
rule = "codelingo/go/break-select-in-for"
sha = "171c416fac02516604e48d2e65153dd55a12513e"

[[issues]]
  filepath = "vendor/google.golang.org/grpc/balancer.go"
  fileline = 336
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
