repo = "github.com/caddyserver/caddy"
rule = "codelingo/go/default-in-type-switch"
sha = "891446d06340db2912c9a970bfe862bd54efbb70"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 138
  filepath = "caddyfile/json.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 127
  filepath = "caddyhttp/gzip/setup_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 328
  filepath = "telemetry/telemetry.go"
  fixed = false
  ignored = "fallthrough"
