repo = "github.com/edumco/docker-slim"
rule = "codelingo/go/unchecked-type-assertion"
sha = "abba44d7e861c3df3f495315b5a73b21a8dd3ef0"

[[issues]]
  filepath = "internal/app/sensor/app.go"
  fileline = 168
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/docker/dockerimage/topobjects.go"
  fileline = 28
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/docker/dockerimage/topobjects.go"
  fileline = 44
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ipc/command/command.go"
  fileline = 88
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
