repo = "github.com/SimonWaldherr/ups"
rule = "codelingo/go/unchecked-type-assertion"
sha = "d3e0fc2485f52550d12a96ae00b44a25738eb42e"

[[issues]]
  fileline = 77
  filepath = "load.go"
  fixed = false
  ignored = "fp"
