repo = "github.com/ngchain/ngcore"
rule = "codelingo/code-review-comments/camel-case-constants"
sha = "16e762e18441963bdb7adf2b32e6f13830196e69"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 37
  comment = "Define constant \"TxType_APPEND\" as \"TxtypeAppend\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 33
  comment = "Define constant \"TxType_REGISTER\" as \"TxtypeRegister\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 34
  comment = "Define constant \"TxType_LOGOUT\" as \"TxtypeLogout\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 35
  comment = "Define constant \"TxType_TRANSACTION\" as \"TxtypeTransaction\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 32
  comment = "Define constant \"TxType_GENERATE\" as \"TxtypeGenerate\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 36
  comment = "Define constant \"TxType_ASSIGN\" as \"TxtypeAssign\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"

[[issues]]
  filepath = "ngtypes/types.pb.go"
  fileline = 31
  comment = "Define constant \"TxType_INVALID\" as \"TxtypeInvalid\". The convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword constant names. [as specified in Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps)"
