repo = "github.com/cnlh/nps"
rule = "codelingo/go/non-directional-chan"
sha = "c9b755360c3b3513e53bb265ae49703f06d6f34f"

[[issues]]
  filepath = "lib/pmux/plistener.go"
  fileline = 15
  comment = "Returned channels or channel arguments should generally have a direction."
