repo = "github.com/json-iterator/go"
rule = "codelingo/go/default-in-type-switch"
sha = "53b9d06ba7ca7edaa0d08a1c5acb0ef75c91eed4"

[[issues]]
  filepath = "reflect_json_number.go"
  fileline = 26
  comment = "Always include a default case when using a type switch."
