repo = "github.com/edumco/docker-slim"
rule = "codelingo/go/reassigned-error"
sha = "abba44d7e861c3df3f495315b5a73b21a8dd3ef0"

[[issues]]
  filepath = "pkg/util/fsutil/fsutil.go"
  fileline = 820
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "internal/app/master/update/update.go"
  fileline = 317
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "pkg/util/fsutil/fsutil.go"
  fileline = 869
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "internal/app/master/inspectors/container/probes/http/custom_probe.go"
  fileline = 261
  comment = "Error was not checked before reassignment"
