repo = "github.com/arthurkiller/rollingwriter"
rule = "codelingo/go/non-directional-chan"
sha = "0c781a15588e265e57e6bc5c4a0efd070a72a6ac"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 42
  filepath = "rollingwriter.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 78
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 237
  filepath = "writer.go"
  fixed = false
  ignored = "fp"
