repo = "github.com/gadelkareem/awsgo"
rule = "missing-close-file"
sha = "8f0a586ce8206840c11d27b56a938ac9ef92622e"

[[issues]]
  fileline = 61
  filepath = "AwsService.go"
  fixed = true
  ignored = ""
