repo = "github.com/sundy-li/html2article"
rule = "missing-close-file"
sha = "09ac198090c224161026f4a4b7bb4ddce402cea6"

[[issues]]
  fileline = 11
  filepath = "stopwords.go"
  fixed = true
  ignored = ""
