repo = "github.com/bilibili/kratos"
rule = "codelingo/go/default-in-type-switch"
sha = "8de8758d3d5f40ea047de945c5969fab59a2acda"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 206
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough as default"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 53
  filepath = "pkg/cache/redis/pubsub_test.go"
  fixed = false
  ignored = "ignore invalid type"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 81
  filepath = "tool/testgen/parser.go"
  fixed = false
  ignored = "invalid ignored"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 100
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 286
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 140
  filepath = "pkg/conf/paladin/value_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 180
  filepath = "tool/testgen/parser.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 180
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 15
  filepath = "pkg/time/time.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 129
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 40
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 237
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 149
  filepath = "pkg/cache/memcache/encoding.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 154
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 256
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 62
  filepath = "pkg/conf/paladin/value_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 130
  filepath = "tool/testgen/parser.go"
  fixed = false
  ignored = "fallthrough"

[[issues]]
  comment = "Always include a default case when using a type switch."
  fileline = 71
  filepath = "pkg/cache/redis/reply.go"
  fixed = false
  ignored = "fallthrough"
