repo = "github.com/Netflix/chaosmonkey"
rule = "codelingo/go/unchecked-type-assertion"
sha = "68e3282ef73c39c9ae998185f526cc2713c612d1"

[[issues]]
  filepath = "config/monkey.go"
  fileline = 324
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 170
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "config/monkey.go"
  fileline = 462
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 90
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 150
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 195
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "mysql/mysql.go"
  fileline = 46
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 130
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "spinnaker/terminator_test.go"
  fileline = 65
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 106
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "spinnaker/terminator_test.go"
  fileline = 160
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "term/terminate_test.go"
  fileline = 55
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
