repo = "github.com/apex/up"
rule = "codelingo/go/ticker-in-for-select"
sha = "5777a4ff5f92b7d2e1119c79263d57c2a5573557"

[[issues]]
  filepath = "internal/util/util.go"
  fileline = 215
  comment = "Make one ticker as opposed to making a new timer each iteration."
