repo = "github.com/SimonWaldherr/golang-examples"
rule = "codelingo/go/non-directional-chan"
sha = "700550ebe223c21b8c1118785617a13336502b75"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 61
  filepath = "expert/pi2go.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 90
  filepath = "expert/pi2go-live.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 119
  filepath = "expert/dynparallel.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 78
  filepath = "expert/pi2go.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 43
  filepath = "expert/pi2go-live.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 22
  filepath = "expert/pi2go.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 24
  filepath = "expert/pi2go-live.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 9
  filepath = "advanced/getchar.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 9
  filepath = "advanced/getchar.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 36
  filepath = "expert/pi2go.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 28
  filepath = "advanced/fanin.go"
  fixed = false
  ignored = "fp"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 70
  filepath = "expert/pi2go-live.go"
  fixed = true
  ignored = ""
