repo = "github.com/grafana/loki"
rule = "codelingo/go/reassigned-error"
sha = "8e5fa03de3b3cf7efa15e4959bd5b7decae2d944"

[[issues]]
  filepath = "cmd/chunks-inspect/loki.go"
  fileline = 116
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "cmd/chunks-inspect/loki.go"
  fileline = 114
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "cmd/chunks-inspect/loki.go"
  fileline = 114
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "cmd/chunks-inspect/loki.go"
  fileline = 115
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "cmd/chunks-inspect/loki.go"
  fileline = 152
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "pkg/loghttp/series.go"
  fileline = 16
  comment = "Error was not checked before reassignment"
