repo = "github.com/flynn/flynn"
rule = "codelingo/go/insecure-http-connection"
sha = "755c95684ffe290c64b8be114c2963aa2850b531"

[[issues]]
  filepath = "discoverd/health/check.go"
  fileline = 75
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "pkg/pinned/pinned.go"
  fileline = 41
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "test/test_router.go"
  fileline = 92
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "host/logmux/sink.go"
  fileline = 550
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
