repo = "github.com/hashicorp/consul"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "aae14b39514d7d4e0537d35308d6959f35bfbc48"

[[issues]]
  filepath = "command/debug/debug_test.go"
  fileline = 92
  comment = "Close the file when you are done"
