repo = "github.com/edumco/docker-slim"
rule = "codelingo/go/insecure-http-connection"
sha = "abba44d7e861c3df3f495315b5a73b21a8dd3ef0"

[[issues]]
  filepath = "internal/app/master/inspectors/container/probes/http/custom_probe.go"
  fileline = 169
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
