repo = "github.com/HiepPP/golang-practice-basic"
rule = "codelingo/go/non-directional-chan"
sha = "afba2478c6adaa3c1f49071e93d0b9147122dfc5"

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 37
  filepath = "concurent/goroutine3.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 23
  filepath = "concurent/concurent4.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Returned channels or channel arguments should generally have a direction."
  fileline = 32
  filepath = "concurent/goroutine2.go"
  fixed = false
  ignored = "fp"
